import {
  ArrowRight,
  ChevronRight,
  Droplet,
  Flower2,
  Heart,
  Home,
  Lock,
  Menu,
  Moon,
  Play,
  Plus,
  Quote,
  Search,
  ShieldCheck,
  ShoppingBag,
  Sparkles,
  Star,
  Sun,
  Truck,
  type LucideProps,
  User,
  Wind,
  X,
  Zap,
} from '@/components/ui/icon';

// Storefront `Icon.*` set, now backed by Lucide (docs/design/icon-system.md).
// Keys are frozen so existing call sites keep working; new code should import
// from '@/components/ui/icon' directly.
type P = LucideProps;

export const Icon = {
  // Key frozen for call-site compat; renders Flower2 (leaf/sprout glyphs retired).
  leaf: (p: P) => <Flower2 strokeWidth={2} {...p} />,
  truck: (p: P) => <Truck strokeWidth={2} {...p} />,
  shield: (p: P) => <ShieldCheck strokeWidth={2} {...p} />,
  star: (p: P) => <Star fill="currentColor" strokeWidth={0} {...p} />,
  arrow: (p: P) => <ArrowRight strokeWidth={2} {...p} />,
  bag: (p: P) => <ShoppingBag strokeWidth={2} {...p} />,
  menu: (p: P) => <Menu strokeWidth={2} {...p} />,
  x: (p: P) => <X strokeWidth={2} {...p} />,
  play: (p: P) => <Play fill="currentColor" strokeWidth={2} {...p} />,
  droplet: (p: P) => <Droplet strokeWidth={2} {...p} />,
  sun: (p: P) => <Sun strokeWidth={2} {...p} />,
  spark: (p: P) => <Sparkles strokeWidth={2} {...p} />,
  quote: (p: P) => <Quote fill="currentColor" strokeWidth={0} {...p} />,
  user: (p: P) => <User strokeWidth={2} {...p} />,
  truckFast: (p: P) => <Truck strokeWidth={2} {...p} />,
  lock: (p: P) => <Lock strokeWidth={2} {...p} />,
  chevron: (p: P) => <ChevronRight strokeWidth={2} {...p} />,
  heart: (p: P) => <Heart strokeWidth={2} {...p} />,
  plus: (p: P) => <Plus strokeWidth={2} {...p} />,
  search: (p: P) => <Search strokeWidth={2} {...p} />,
  wind: (p: P) => <Wind strokeWidth={2} {...p} />,
  moon: (p: P) => <Moon strokeWidth={2} {...p} />,
  home: (p: P) => <Home strokeWidth={2} {...p} />,
  zap: (p: P) => <Zap strokeWidth={2} {...p} />,
  sprout: (p: P) => <Flower2 strokeWidth={2} {...p} />,
};
